"""Request/response models for the review API.

Removal requires a reason code -- the build spec calls this Should Have
in the PRD it's replacing and promotes it to Must Have, because those
reasons are labelled evaluation data generated by the workflow itself.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum

from pydantic import BaseModel, ConfigDict, model_validator


class DecisionAction(str, Enum):
    ACCEPT_ALL = "accept_all"
    ACCEPT_SELECTED = "accept_selected"
    REMOVE = "remove"
    EDIT = "edit"
    PHYSICIAN_QUERY = "physician_query"


class ReasonCode(str, Enum):
    DUPLICATE = "duplicate"
    CLINICAL_JUDGMENT = "clinical_judgment"
    PAYER_RULE_EXCEPTION = "payer_rule_exception"
    OTHER = "other"


class DecisionRequest(BaseModel):
    model_config = ConfigDict(extra="forbid")

    actor: str
    action: DecisionAction
    line_id: str | None = None
    reason_code: ReasonCode | None = None
    edit: dict | None = None  # new {units, modifiers} when action == edit
    note: str | None = None

    @model_validator(mode="after")
    def _remove_requires_reason_code(self) -> "DecisionRequest":
        if self.action == DecisionAction.REMOVE and self.reason_code is None:
            raise ValueError("removing a line requires a reason_code")
        if self.action in (DecisionAction.REMOVE, DecisionAction.EDIT) and self.line_id is None:
            raise ValueError(f"action {self.action.value} requires a line_id")
        return self


class DecisionLogEntry(BaseModel):
    model_config = ConfigDict(extra="forbid")

    timestamp: datetime
    case_id: str
    run_id: str
    ruleset_id: str
    actor: str
    action: DecisionAction
    line_id: str | None
    reason_code: ReasonCode | None
    edit: dict | None
    note: str | None
